[project]
name = "wifi-analizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Christopher Negron", email = "sonycar2000@outlook.com" }
]
requires-python = ">=3.11"
dependencies = [
    "comtypes>=1.4.17",
    "matplotlib>=3.11.2",
    "pywifi>=1.1.12",
    "requests>=2.34.2",
    "rich>=15.0.0",
]

[project.scripts]
wifi-analizer = "wifi_analizer:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
